image: archlinux
packages:
  - julia
sources:
  - https://github.com/stev47/OpticalFlowUtils.jl
tasks:
  - instantiate: |
      cd OpticalFlowUtils.jl
      julia --color=yes --project=. -e "using Pkg; Pkg.instantiate()"
  - test: |
      cd OpticalFlowUtils.jl
      julia --color=yes --project=. -e "using Pkg; Pkg.test()"
