name = "OpticalFlowUtils"
uuid = "ab0dad50-ab19-448c-b796-13553ec8b2d3"
authors = ["Stephan Hilb <stephan@ecshi.net>"]
version = "0.3.0"

[deps]
Colors = "5ae59095-9a9b-59fe-a467-6f913c188581"
FileIO = "5789e2e9-d7fb-5bc7-8068-2c6fae9b9549"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"

[compat]
Colors = "^0.13"
FileIO = "^1"
julia = "^1.5"
